#!/bin/bash

function voice_esp32_enable() 
{
	echo 25 > /sys/class/gpio/export 2> /dev/null
	echo 24 > /sys/class/gpio/export 2> /dev/null

	echo out > /sys/class/gpio/gpio25/direction
	echo out > /sys/class/gpio/gpio24/direction

	for i in `seq 50`; do
		sleep 0.5
		echo 1 > /sys/class/gpio/gpio25/value
		echo 1 > /sys/class/gpio/gpio24/value
		echo 1 > /sys/class/gpio/gpio25/value
		echo 0 > /sys/class/gpio/gpio24/value
		echo 1 > /sys/class/gpio/gpio25/value
		echo 1 > /sys/class/gpio/gpio24/value
	done
} 

voice_esp32_enable
