#!/bin/bash -e

echo "Enabling firmware loading at startup"
systemctl enable matrixio-devices-firmware

# This didn't work due to an unresolved shared library.
# Asking users to reboot after installation.
# echo "Loading firmware..."
# service matrixio-devices-firmware start

echo "Enabling SPI"
cp /boot/config.txt /boot/config.txt.bk && /usr/share/matrixlabs/matrixio-devices/matrixlabs_edit_setting.py /boot/config.txt.bk /usr/share/matrixlabs/matrixio-devices/config/boot_modifications.txt > /boot/config.txt

echo "Disable UART console"
/usr/share/matrixlabs/matrixio-devices/matrixlabs_remove_console.py

echo "Please restart your Raspberry Pi after installation"
